# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

_target_: blueprint.trainers.MomentMatchingTrainer
kernel:
  _target_: blueprint.losses.mmd.ExponentialKernel
  p: 1
  n_kernels: 20
  mul_factor: 1.4