# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

defaults:
  - dataset@ds_train: gaussian2spiral
  - dataset@ds_val: gaussian2spiral
  - dataset@ds_test: gaussian2spiral
  - runtime: training
  - trainer: momentmatching
  - optimizer: adamw
  - scheduler: cosineannealing
  - model: momentnet
  - hydra_defaults
  - _self_

n_training_samples: ${eval:2**19}

ds_val:
  sourcedist:
    length: 1024
    seed: 1
  targetdist:
    length: 1024
    seed: 1

ds_test:
  sourcedist:
    length: 1024
    seed: 2
  targetdist:
    length: 1024
    seed: 2

optimizer:
  lr: 0.003

runtime:
  name: momentmatching
  batch_size: 512
